# Generated by Django 4.0.5 on 2022-07-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lywebsocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalserver',
            name='port',
            field=models.IntegerField(default=22, help_text='端口号', verbose_name='端口号'),
        ),
    ]
