# Generated by Django 3.2.6 on 2021-10-27 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.modles


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunbotuManage',
            fields=[
                ('id', models.CharField(default=utils.modles.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('type', models.IntegerField(choices=[(1, '首页轮播图'), (2, '分类首页轮播图')], verbose_name='轮播图类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort', models.IntegerField(default=1, help_text='显示顺序', verbose_name='排序')),
                ('image', models.CharField(default='', max_length=255, verbose_name='图片')),
                ('link', models.CharField(default='', max_length=100, verbose_name='链接')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '轮播图设置',
                'verbose_name_plural': '轮播图设置',
                'db_table': 'tb_lunbo_manage',
            },
        ),
    ]
