# Generated by Django 4.0.3 on 2022-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformsettings', '0003_userleavingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermanage',
            name='type',
            field=models.IntegerField(choices=[(1, '正常'), (2, '富文本'), (3, '图片')], default=1, verbose_name='类型'),
        ),
    ]
