# Generated by Django 4.0.8 on 2022-10-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformsettings', '0003_alter_othermanage_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othermanage',
            options={'verbose_name': '参数设置', 'verbose_name_plural': '参数设置'},
        ),
    ]
