# Generated by Django 4.0.3 on 2022-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformsettings', '0005_alter_othermanage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunbotumanage',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='富文本内容'),
        ),
        migrations.AddField(
            model_name='lunbotumanage',
            name='link_type',
            field=models.IntegerField(choices=[(0, '无'), (1, '链接'), (2, '富文本')], default=0, verbose_name='跳转类型'),
        ),
        migrations.AlterField(
            model_name='lunbotumanage',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='链接'),
        ),
    ]
