# Generated by Django 4.1.4 on 2022-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformsettings', '0006_alter_systemconfig_form_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='data_options',
            field=models.TextField(blank=True, help_text='数据options', null=True, verbose_name='数据options'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='rule',
            field=models.TextField(blank=True, help_text='校验规则', null=True, verbose_name='校验规则'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='setting',
            field=models.TextField(blank=True, help_text='配置', null=True, verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(blank=True, help_text='键值', null=True, verbose_name='键值'),
        ),
    ]
