# Generated by Django 4.0.3 on 2022-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformsettings', '0006_lunbotumanage_content_lunbotumanage_link_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunbotumanage',
            name='content',
        ),
        migrations.AlterField(
            model_name='lunbotumanage',
            name='link',
            field=models.TextField(blank=True, default='', null=True, verbose_name='链接/富文本内容'),
        ),
    ]
