# Generated by Django 4.0.8 on 2022-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='identity',
            field=models.SmallIntegerField(blank=True, choices=[(0, '超级管理员'), (1, '系统管理员'), (2, '前端用户')], default=2, help_text='身份标识', null=True, verbose_name='身份标识'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话', max_length=30, null=True, verbose_name='电话'),
        ),
    ]
