# Generated by Django 4.0.5 on 2022-07-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['create_datetime'], 'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.AlterModelOptions(
            name='skuspecification',
            options={'ordering': ['create_datetime'], 'verbose_name': 'SKU规格', 'verbose_name_plural': 'SKU规格'},
        ),
        migrations.AlterModelOptions(
            name='spuspecification',
            options={'ordering': ['create_datetime'], 'verbose_name': '商品SPU规格', 'verbose_name_plural': '商品SPU规格'},
        ),
        migrations.AlterModelOptions(
            name='spuspecificationoption',
            options={'ordering': ['create_datetime'], 'verbose_name': '规格选项', 'verbose_name_plural': '规格选项'},
        ),
    ]
