# Generated by Django 4.0.5 on 2022-06-27 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthWXUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('xcx_openid', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小程序openid')),
                ('gzh_openid', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='公众号openid')),
                ('avatarUrl', models.CharField(blank=True, max_length=900, null=True, verbose_name='用户头像')),
                ('nick', models.CharField(blank=True, max_length=40, null=True, verbose_name='用户昵称')),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('unionId', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('xcx_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='小程序access_token')),
                ('gzh_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='公众号access_token')),
                ('gzh_refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='公众号refresh_token')),
                ('gzh_scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='公众号scope')),
                ('mobilePhoneNumber', models.CharField(default='', max_length=11, verbose_name='微信小程序绑定的手机号码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信登录用户数据',
                'verbose_name_plural': '微信登录用户数据',
                'db_table': 'tb_oauth_wx',
            },
        ),
    ]
