# Generated by Django 4.0.8 on 2022-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthwxuser',
            name='mobilePhoneNumber',
            field=models.CharField(default='', max_length=30, verbose_name='微信小程序绑定的手机号码（国外手机号会有区号）'),
        ),
    ]
