# Generated by Django 4.1.8 on 2023-11-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('citycode', models.CharField(blank=True, db_index=True, help_text='城市编码', max_length=20, null=True, verbose_name='城市编码')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='地区层级(1省份 2城市 3区县 4乡镇/街道级)')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='address.area', verbose_name='上级行政区划')),
            ],
            options={
                'verbose_name': '省市区',
                'verbose_name_plural': '省市区',
                'db_table': 'tb_areas',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('receiver', models.CharField(blank=True, max_length=20, null=True, verbose_name='收货人')),
                ('province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=32, null=True, verbose_name='区')),
                ('street', models.CharField(blank=True, max_length=32, null=True, verbose_name='街道')),
                ('place', models.CharField(max_length=50, verbose_name='收货地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'tb_address',
            },
        ),
    ]
