# Generated by Django 3.2.9 on 2022-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
