# Generated by Django 4.0.3 on 2022-04-02 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_area_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
                ('receiver', models.CharField(blank=True, max_length=20, null=True, verbose_name='收货人')),
                ('province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=32, null=True, verbose_name='区')),
                ('street', models.CharField(blank=True, max_length=32, null=True, verbose_name='街道')),
                ('place', models.CharField(max_length=50, verbose_name='收货地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'tb_address',
            },
        ),
    ]
